# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build
language: node_js
node_js:
  - "9"

sudo: required

services:
  - docker

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@latest
  - sudo apt-get update && sudo apt-get install curl

install:
  - npm ci

before_script:
  - npm run stylelint
  - npm run lint
  - npm run unit

script:
  - npm run build
  - docker build -t RaudseppSiim/Pipeline-testing .

after_script:
  - docker ps
  - docker run -d --name Pipeline-testing -p "8081:80" RaudseppSiim/Pipeline-testing
  - docker ps
  - curl "http://localhost:8081/index.html"
